import glob
import os
import time
import uuid
import matplotlib.pyplot as plt
from typing import Dict, Any, List
import logging

import pandas as pd
import psutil
from langchain_core.messages import AIMessage
from pandasai import SmartDataframe
from pandasai.llm.local_llm import LocalLLM

# FIX LOGGING ERRORS ON WINDOWS
logging.disable(logging.CRITICAL)

class ChartDrawingAgent:
    def __init__(
        self,
        llm,   # <-- this is your ChatOllama / ChatGPT model
        model_url="http://localhost:11434/v1",
        model_name="gpt-oss:20b-cloud",
        data_root=r"D:\UsingSpace\Projects\Artificial Intelligent\Agent\Data Analytics Agent\backend\uploads"
    ):
        self.llm = llm  # <-- used ONLY for analysis, decomposition

        # PandasAI chart generator stays EXACTLY like in your old code
        self.pandas_llm = LocalLLM(
            api_base=model_url,
            model=model_name
        )

        self.data_root = data_root

    # ---------------------------------------------------------
    # 1️⃣ Use ChatOllama to split into chart tasks
    # ---------------------------------------------------------
    def split_into_chart_tasks(self, command: str) -> List[str]:
        prompt = f"""
            Your task is to understand this request and make it into smaller draw chart subtask.
            
            Break this request into separate chart instructions. Only do it if it asked for multiple charts drawing. Don't try too hard to break everything in to minor graphs.:            {command}
            
            Return in this exact format and nothing else so i can handle it:
            <request to draw chart 1>|<request to draw chart 2>|etc.
            Example:
            Draw line charts sales this month|Draw bar charts for ages of users|etc.
        """
        raw = self.llm.invoke(prompt)  # <-- your ChatOllama
        # print("Chart drawing commands",raw)

        # try:
        #     tasks = eval(raw)
        #     if not isinstance(tasks, list):
        #         tasks = [command]
        # except:
        #     tasks = [command]

        tasks_raw = raw.content
        tasks = tasks_raw.split("|")

        print(tasks)
        return tasks

    # ---------------------------------------------------------
    # 2️⃣ Use PandasAI to execute ONE chart task
    # ---------------------------------------------------------
    def generate_single_chart(self, task: str, out_dir: str):
        sdf = self.sdf

        before_procs = {p.pid for p in psutil.process_iter()}

        chart_result = sdf.chat(task)

        time.sleep(0.5)  # small delay to allow OS to spawn viewer
        for p in psutil.process_iter(['pid', 'name', 'exe', 'cmdline']):
            if p.info['pid'] not in before_procs:
                name = (p.info['name'] or "").lower()
                cmd = " ".join(p.info['cmdline'] or [])
                # check common image apps / Office apps
                if any(x in name for x in ["photos", "mspaint", "excel", "powerpnt", "chrome"]):
                    try:
                        p.kill()
                        print(f"Killed auto-opened process: {name} ({p.info['pid']})")
                    except Exception:
                        pass

        # chart_path = None
        #
        # if isinstance(chart_result, dict) and chart_result.get("type") == "plot":
        #     # PandasAI should return a path string for "plot" type
        #     chart_path = chart_result["value"]
        #     if not os.path.isabs(chart_path):
        #         chart_path = os.path.join(out_dir, chart_path)
        #     print(f"Chart saved to {os.path.abspath(chart_path)}")
        # else:
        #     print("No chart was generated by PandasAI or returned value is not of type 'plot'.")

        # return chart_path

    def load_dataframe(self, filename: str) -> pd.DataFrame:
        """
        Load a dataframe from a file in DATA_PARENT_DIR.
        Supports CSV and Excel files.
        """
        path = os.path.join(self.data_root, filename)

        if not os.path.exists(path):
            raise FileNotFoundError(f"File not found: {path}")

        # File type detection
        ext = filename.lower().split(".")[-1]

        if ext == "csv":
            return pd.read_csv(path)

        elif ext in ["xlsx", "xls"]:
            return pd.read_excel(path)

        else:
            raise ValueError(
                f"Unsupported file format '{ext}'. Only CSV or Excel is allowed."
            )

    # ---------------------------------------------------------
    # 3️⃣ LangGraph node entry point
    # ---------------------------------------------------------
    def __call__(self, state: Dict[str, Any]) -> Dict[str, Any]:
        print("CHART DRAWING AGENT")

        df = self.load_dataframe(state['file_name'])
        command = state["command"]
        out_dir = state.get("output_dir", "./charts")
        os.makedirs(out_dir, exist_ok=True)

        # Split into chart tasks using ChatOllama
        tasks = self.split_into_chart_tasks(command)

        # Execute each task using PandasAI + LocalLLM
        user_defined_path = "charts/"
        config = {
            "llm": self.pandas_llm,
            "enable_cache": False,
            "save_charts": True,
            "save_charts_path": user_defined_path,
            "show_charts": False,  # still set, won't hurt
            "output": "plot"
        }
        self.sdf = SmartDataframe(df, config=config)

        chart_paths = []
        for t in tasks[0:3]:
            self.generate_single_chart(t, out_dir)
        chart_paths = glob.glob(os.path.join(user_defined_path, "*"))
        print(chart_paths)

        return {
            # "agent_responses": [AIMessage(content=f"Finished drawing graphs. Drew {len(chart_paths)} images")],
            "agent_responses": [
                AIMessage(
                    content=f"Finished drawing graphs you have asked for. The visualization task has been done very well. You should move on to analyze charts using chart_analysis_agent."
                )
            ],
        }
